using Rental.Domain.Enums;

namespace Rental.Domain.Applications.Models;

public record RentalApplication(
    string RentalAddress,
    string? OtherApplicants,
    PersonalInfo PersonalInfo,
    RentalReference CurrentRental,
    EmploymentInfo PrimaryEmployment,
    EmploymentInfo SecondaryEmployment,
    ParentInfo ParentInfo,
    YesNo? ConsiderOtherIncome,
    string? OtherIncomeExplain,
    Automobile Automobile,
    RentalReference PriorRentRef1,
    PersonalReference PersonalReference1,
    PersonalReference PersonalReference2,
    string AnticipatedDuration,
    YesNo? HasCriminalRecord,
    string? ExplainCriminalRecord,
    YesNo? HasBeenEvicted,
    string? ExplainBeenEvicted,
    YesNo? MarijuanaCard,
    YesNo? Smokers,
    int? SmokersCount,
    YesNo? Drinkers,
    HowOften? HowOftenDrink,
    YesNo? AnyPets,
    string? DescribePets,
    YesNo? AnyNonHuman,
    string? DescribeNonHuman,
    YesNo? AttendCollege,
    int? CollegeYearsAttended,
    string? PlanToGraduate,
    YesNo? NeedReasonableAccommodation,
    string? DescribeReasonableAccommodation,
    bool AcceptedTerms,
    string? AdditionalComments
);
